version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./tests/unmocked_unit_tests.py
          name: unmocked tests
      - run:
          command: python ./tests/mocked_unit_tests.py
          name: mocked tests

workflows:
  main:
    jobs:
      - build-and-test
